import 'package:path/path.dart' as p;

import '../analyzer/cross_reference.dart';

class LocalGenerator {
  static String generate(
    Map<String, dynamic> structure, {
    Map<String, List<String>>? dependencyGraph,
  }) {
    final buffer = StringBuffer();
    final filePath = structure['file'] as String;
    final fileName = p.basenameWithoutExtension(filePath);

    buffer.writeln('# $fileName');
    buffer.writeln();
    buffer.writeln('> Auto-generated by docgen');
    buffer.writeln();
    buffer.writeln('**Source:** `$filePath`');
    buffer.writeln();

    // Dependency info
    if (dependencyGraph != null) {
      final depSection = CrossReferenceAnalyzer.generateDependencySection(
        filePath,
        dependencyGraph,
      );
      if (depSection.isNotEmpty) {
        buffer.write(depSection);
      }
    }

    // Classes
    final classes = structure['classes'] as List<dynamic>? ?? [];
    for (final cls in classes) {
      _writeClass(buffer, cls as Map<String, dynamic>);
    }

    // Top-level functions
    final functions = structure['topLevelFunctions'] as List<dynamic>? ?? [];
    if (functions.isNotEmpty) {
      buffer.writeln('## Top-Level Functions');
      buffer.writeln();
      _writeMethodTable(buffer, functions.cast<Map<String, dynamic>>());
    }

    return buffer.toString();
  }

  static void _writeClass(StringBuffer buffer, Map<String, dynamic> cls) {
    final name = cls['name'] as String;
    final constructors = cls['constructors'] as List<dynamic>? ?? [];
    final methods = cls['methods'] as List<dynamic>? ?? [];

    buffer.writeln('## $name');
    buffer.writeln();

    // Constructors
    if (constructors.isNotEmpty) {
      buffer.writeln('### Constructors');
      buffer.writeln();
      for (final ctor in constructors) {
        final ctorMap = ctor as Map<String, dynamic>;
        final ctorName = ctorMap['name'] as String;
        final params = ctorMap['parameters'] as List<dynamic>? ?? [];
        final paramStr = _formatParams(params);
        buffer.writeln('```dart');
        buffer.writeln('$ctorName($paramStr)');
        buffer.writeln('```');
        buffer.writeln();
      }
    }

    // Methods
    if (methods.isNotEmpty) {
      buffer.writeln('### Methods');
      buffer.writeln();
      _writeMethodTable(buffer, methods.cast<Map<String, dynamic>>());

      // Usage example
      buffer.writeln('### Usage Example');
      buffer.writeln();
      buffer.writeln('```dart');
      _writeUsageExample(buffer, name, constructors, methods);
      buffer.writeln('```');
      buffer.writeln();
    }
  }

  static void _writeMethodTable(
    StringBuffer buffer,
    List<Map<String, dynamic>> methods,
  ) {
    buffer.writeln('| Method | Parameters | Return Type |');
    buffer.writeln('|--------|-----------|-------------|');

    for (final method in methods) {
      final name = method['name'] as String;
      final returnType = method['returnType'] as String? ?? 'void';
      final params = method['parameters'] as List<dynamic>? ?? [];
      final paramStr = _formatParamsShort(params);
      buffer.writeln('| `$name` | $paramStr | `$returnType` |');
    }

    buffer.writeln();
  }

  static void _writeUsageExample(
    StringBuffer buffer,
    String className,
    List<dynamic> constructors,
    List<dynamic> methods,
  ) {
    final instanceName =
        className[0].toLowerCase() + className.substring(1);

    // Constructor call
    if (constructors.isNotEmpty) {
      final ctor = constructors.first as Map<String, dynamic>;
      final params = ctor['parameters'] as List<dynamic>? ?? [];
      final args = params.map((p) {
        final param = p as Map<String, dynamic>;
        final name = param['name'] as String;
        final type = param['type'] as String;
        return '  $name: ${_placeholderForType(type)},';
      }).join('\n');

      if (args.isNotEmpty) {
        buffer.writeln('final $instanceName = $className(');
        buffer.writeln(args);
        buffer.writeln(');');
      } else {
        buffer.writeln('final $instanceName = $className();');
      }
    } else {
      buffer.writeln('final $instanceName = $className();');
    }

    buffer.writeln();

    // First few method calls
    final methodsToShow = methods.take(3);
    for (final m in methodsToShow) {
      final method = m as Map<String, dynamic>;
      final name = method['name'] as String;
      final returnType = method['returnType'] as String? ?? 'void';
      final params = method['parameters'] as List<dynamic>? ?? [];

      final args = params.map((p) {
        final param = p as Map<String, dynamic>;
        final type = param['type'] as String;
        return _placeholderForType(type);
      }).join(', ');

      if (returnType != 'void' && returnType != 'Future<void>') {
        buffer.writeln('final result = await $instanceName.$name($args);');
      } else {
        buffer.writeln('await $instanceName.$name($args);');
      }
    }
  }

  static String _formatParams(List<dynamic> params) {
    if (params.isEmpty) return '';
    return params.map((p) {
      final param = p as Map<String, dynamic>;
      return '${param['type']} ${param['name']}';
    }).join(', ');
  }

  static String _formatParamsShort(List<dynamic> params) {
    if (params.isEmpty) return '—';
    return params.map((p) {
      final param = p as Map<String, dynamic>;
      return '`${param['type']}` ${param['name']}';
    }).join(', ');
  }

  static String _placeholderForType(String type) {
    if (type.contains('String')) return "'...'";
    if (type.contains('int')) return '0';
    if (type.contains('double')) return '0.0';
    if (type.contains('bool')) return 'true';
    if (type.contains('List')) return '[]';
    if (type.contains('Map')) return '{}';
    if (type.contains('Duration')) return 'Duration(seconds: 30)';
    return '/* $type */';
  }
}
