import 'dart:io';

/// Loads and applies custom documentation templates.
///
/// Users can create a `.docgen-template.md` in their project root
/// to customize the output format.
///
/// Template variables:
///   {{FILE_NAME}}       - Source file name
///   {{FILE_PATH}}       - Full source path
///   {{CLASS_NAME}}      - Class name (repeated per class)
///   {{CONSTRUCTORS}}    - Constructor signatures
///   {{METHODS_TABLE}}   - Markdown table of methods
///   {{USAGE_EXAMPLE}}   - Auto-generated usage example
///   {{DEPENDENCIES}}    - Dependency info (uses/used-by)
///   {{GENERATED_AT}}    - Timestamp
class TemplateEngine {
  static const _templateFile = '.docgen-template.md';

  static const defaultTemplate = '''
# {{FILE_NAME}}

> Auto-generated by docgen | {{GENERATED_AT}}

**Source:** `{{FILE_PATH}}`

{{#CLASSES}}
## {{CLASS_NAME}}

{{CONSTRUCTORS}}

{{METHODS_TABLE}}

{{DEPENDENCIES}}

{{USAGE_EXAMPLE}}

{{/CLASSES}}

{{#TOP_LEVEL_FUNCTIONS}}
## Top-Level Functions

{{METHODS_TABLE}}
{{/TOP_LEVEL_FUNCTIONS}}
''';

  static String? _cachedTemplate;

  /// Loads custom template or returns default.
  static String loadTemplate() {
    if (_cachedTemplate != null) return _cachedTemplate!;

    final file = File(_templateFile);
    if (file.existsSync()) {
      _cachedTemplate = file.readAsStringSync();
      return _cachedTemplate!;
    }

    return defaultTemplate;
  }

  /// Applies variables to template string.
  static String apply(String template, Map<String, String> variables) {
    var result = template;
    for (final entry in variables.entries) {
      result = result.replaceAll('{{${entry.key}}}', entry.value);
    }
    // Clean up any remaining unresolved variables
    result = result.replaceAll(RegExp(r'\{\{[^}]+\}\}'), '');
    return result;
  }

  /// Checks if a custom template exists.
  static bool get hasCustomTemplate => File(_templateFile).existsSync();

  /// Creates a default template file for the user to customize.
  static Future<void> createDefaultTemplate() async {
    final file = File(_templateFile);
    if (file.existsSync()) {
      print('⚠️  .docgen-template.md already exists.');
      return;
    }
    await file.writeAsString(defaultTemplate);
    print('✅ Created .docgen-template.md - customize it for your team.');
  }
}
